builds:
  - binary: whatchanged
    main: ./cmd/whatchanged/main.go
    goos:
      - windows
      - darwin
      - linux
      - openbsd
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
      - "386"
    goarm:
      - "5"
      - "6"
      - "7"
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
      - -trimpath

archives:
  - files:
      - lib/*.dll
      - lib/*.so
      - lib/*.dylib
      - lib/*.h
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"

release:
  extra_files:
    - glob: lib/*.dll
    - glob: lib/*.so
    - glob: lib/*.dylib
    - glob: lib/*.h