name: ci

on: [push, pull_request]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        go: ["^1.15.0"]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    name: Go ${{ matrix.go }} in ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Environment
        run: |
          go version
          go env

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.33.0
          args: --timeout=5m30s

      # - name: Format
      #   run: make format-check

      - name: Test
        run: |
          make test
          go mod tidy
          git checkout ./

      - name: Build
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist --skip-publish --skip-validate

      - name: Generate changelog
        run: |
          go run -mod=vendor ./cmd/whatchanged/main.go HEAD~

  release:
    name: Release to Github
    if: startsWith(github.ref, 'refs/tags/') && github.repository == 'axetroy/whatchanged'
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Generate release.md
        run: |
          ./cmd/whatchanged/run.sh --tpl=release.tpl --output=release.md
          cat release.md

      - name: Release to Github
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist --release-notes=./release.md
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Prepare publish
        env:
          GITHUB_REF: ${{ github.ref }}
        run: |
          cp README.md ./npm/README.md
          cp release.md ./npm/CHANGELOG.md
          cp LICENSE ./npm/LICENSE
          node ./npm/scripts/bump.js

      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          package: ./npm/package.json
          token: ${{ secrets.NPM_TOKEN }}